version: "3.8"

networks: # 創建Asar專用的Docker Network
  default:
    name: asar-prod

volumes:
  rasa:    # 存放聊天機器人服務的資料
  actions: # 存放動作代理服務的資料
  data:    # 存放後端API服務的資料

services:
  rasa: # 聊天機器人服務
    image: devilhyt/rasa:custom
    volumes:
      - rasa:/app
      - data:/data
    ports:
      - 5005:5005

  action: # 動作代理服務
    image: devilhyt/rasa-sdk:custom
    volumes:
      - actions:/app/actions
    ports:
      - 5055:5055
    privileged: true

  api: # 後端API服務
    image: devilhyt/asar-api:latest
    volumes:
      - actions:/actions
      - data:/data
    environment:
      SECRET_KEY: # Flask密鑰
      # 密鑰可用此指令生成
      # python -c 'import secrets; print(secrets.token_hex())'
      ASAR_USERNAME: admin # 管理員帳號
      ASAR_PASSWORD: admin # 管理員密碼
      RASA_API_HOST: rasa # 聊天機器人服務的別名
      ASAR_API_HOST: api # 後端API服務的別名
    ports:
      - 5500:5500

  web: # 前端網頁服務
    image: devilhyt/asar-web:latest
    environment:
      RASA_API_HOST: rasa # 聊天機器人服務的別名
      ASAR_API_HOST: api # 後端API服務的別名
    ports:
      - 80:80
    depends_on:
      - api

  # tunnel:
  #   image: cloudflare/cloudflared:latest
  #   command: "tunnel --no-autoupdate run"
  #   environment:
  #     TUNNEL_TOKEN:
