version: "3.8"

volumes:
  api-vscode-ext:

networks:
  rasa:

services:
  app:
    container_name: app
    image: rasa:custom
    command: "run -vv --enable-api"
    volumes:
      - ./rasa/app:/app
      - ./api/data:/data
    networks:
      - rasa
    ports:
      - 5005:5005
    restart: unless-stopped

  action:
    container_name: action
    image: rasa-sdk:custom
    command: "start --actions actions --auto-reload"
    volumes:
      - ./rasa/app/actions:/app/actions
    networks:
      - rasa
    ports:
      - 5055:5055
    restart: unless-stopped

  api:
    container_name: api
    image: asar-api:latest
    command:
      [
        "--worker-class=gthread",
        "--workers=1",
        "--threads=4",
        "--reload",
        "--access-logfile=-",
        "--access-logformat='%({x-forwarded-for}i)s %(h)s %(l)s %(u)s %(t)s \"%(r)s\" %(s)s %(b)s \"%(f)s\" \"%(a)s\"'",
        "--log-level=debug",
        "--bind=0.0.0.0:5500",
        "asar_api:create_app()",
      ]
    volumes:
      - ./api/app:/app
      - ./api/data:/data
      - ./rasa/app:/rasa-app
      - api-vscode-ext:/root/.vscode-server/extensions
    environment:
      SECRET_KEY:
      RASA_API_PROTOCOL: http
      RASA_API_HOST: app
      RASA_API_PORT: 5005
      ASAR_API_PROTOCOL: http
      ASAR_API_HOST: api
      ASAR_API_PORT: 5500
      RASA_APP_ROOT: /rasa-app
    networks:
      - rasa
    ports:
      - 5500:5500
    restart: unless-stopped

  web:
    container_name: web
    image: asar-web:latest
    environment:
      ASAR_API_PROTOCOL: http
      ASAR_API_HOST: api
      ASAR_API_PORT: 5500
    networks:
      - rasa
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - api

  tunnel:
    container_name: tunnel
    image: cloudflare/cloudflared:latest
    command: "tunnel --no-autoupdate run"
    environment:
      TUNNEL_TOKEN:
    networks:
      - rasa
    restart: unless-stopped

# docker run -it --rm -v $(pwd)/rasa/app:/app rasa:base init
