version: "3.8"

volumes:
  api-vscode-ext:

networks:
  rasa:

services:
  app:
    image: rasa:custom
    command: "run --enable-api"
    volumes:
      - ~/app:/app
    networks:
      - rasa
    ports:
      - 5005:5005

  action:
    image: rasa-sdk:custom
    command: "start --actions actions --auto-reload"
    volumes:
      - ~/app/actions:/app/actions
    networks:
      - rasa
    ports:
      - 5055:5055

  api:
    image: asar-api:latest
    command:
      [
        "--reload",
        "--access-logfile=-",
        "--access-logformat='%({x-forwarded-for}i)s %(h)s %(l)s %(u)s %(t)s \"%(r)s\" %(s)s %(b)s \"%(f)s\" \"%(a)s\"'",
        "--log-level=debug",
        "--bind=0.0.0.0:5500",
        "asar_api:create_app()",
      ]
    volumes:
      - ./api/app:/app
      - ./api/data:/data
      - api-vscode-ext:/root/.vscode-server/extensions
    networks:
      - rasa
    ports:
      - 5500:5500
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    command: "tunnel --no-autoupdate run"
    environment:
      TUNNEL_TOKEN:
    networks:
      - rasa
    restart: unless-stopped

# docker run -it --rm --network rasa --net-alias rasa -p 5005:5005 -v ~/app:/app rasa:custom shell
# docker run -it --rm --network rasa --net-alias action -p 5055:5055 -v ~/app/actions:/app/actions rasa-sdk:custom start -v -vv --actions actions
