version: '3.8'

services:
  app:
    image: rasa:custom
    command: "run --enable-api"
    volumes:
      - ~/app:/app
    networks:
      - rasa
    ports:
      - 5005:5005
    
  action:
    image: rasa-sdk:custom
    command: "start --actions actions --auto-reload"
    volumes:
      - ~/app/actions:/app/actions
    networks:
      - rasa
    ports:
      - 5055:5055
  
  api:
    image: wingman-api:latest
    command: ["--bind", "0.0.0.0:5500", "wingman_api:create_app()"]
    volumes:
      - ./api/app:/app
    networks:
      - rasa
    ports:
      - 5500:5500
networks:
  rasa:
  
# docker run -it --rm --network rasa --net-alias rasa -p 5005:5005 -v ~/app:/app rasa:custom shell
# docker run -it --rm --network rasa --net-alias action -p 5055:5055 -v ~/app/actions:/app/actions rasa-sdk:custom start -v -vv --actions actions