# builder stage
FROM rasa/rasa:3.6.9-full AS builder

# Change back to root to install dependencies
USER root

# install packages.
RUN set -eux; \
        python -m venv /opt/venv; \
        . /opt/venv/bin/activate; \
        pip install -U --no-cache-dir \
            --extra-index-url https://download.pytorch.org/whl/cpu \
            torch==2.0.1+cpu \
            ckip-transformers \
            line-bot-sdk \
        ;

# release stage
FROM rasa/rasa:3.6.9-full AS release

# Change back to root to install dependencies
USER root

# python venv
COPY --from=builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# replace initial project
COPY ./build/initial_project_zh /app

# set HOME
ENV HOME=/app
WORKDIR /app

# create volumes
VOLUME ["/tmp", "/app", "/data"]

# change shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# the entry point
EXPOSE 5005
ENTRYPOINT ["rasa"]
CMD ["run", "--enable-api", "--cors=\"*\""]
